### ISSUE TITLE
ng-leaflet-universal not working Angular 13+ 

### ISSUE THREAD

**Issue by robomike** [rareyesrd/ng-leaflet-universal#1]
Hi,

The ng-leaflet-universal is not working in Angular 13, when will that be available?

**Comment by JeffreyArt1** [comment]
Same here.

**Comment by JeffreyArt1** [comment]
Any update on this?

**Comment by rareyesrd** [comment]
Angular 13 support on ng-leaflet-universal is already fixed! we'll working on Angular 14 later.
